### ISSUE TITLE
Remove the second manual wp_enqueue_scripts call

### ISSUE THREAD

**Issue by davekiss** [davekiss/vimeography#13]
in renderer.php

**Comment by liquidguru** [comment]
I'm having the same problem. With Vimeography plugin and Google Maps Widget on the same page I get:

Warning: Invalid argument supplied for foreach() in /home/diveinto/public_html/diveintolembeh.com/wp-content/plugins/google-maps-builder/includes/class-gmb-engine.php on line 192

The author of Vimeography tells me it's a fault with Vimeography plugin.

**Comment by davekiss** [comment]
Closed via https://github.com/davekiss/vimeography/commit/389b7869d388adaab389a97727d41cad0dc38697
