### ISSUE TITLE
Full screen autoplay broken

### ISSUE THREAD

**Issue by justincone** [davekiss/vimeography#17]
**URL:** http://motionographer.com/inspiration/

**Steps to reproduce the issue:**
1. Click on a video to launch the player. 
2. Go fullscreen.
3. Wait until end of video. When the next video in the queue starts, there is no video display (only audio). Screenshot attached.

Thanks in advance!

![screenshot-fullscreen](https://cloud.githubusercontent.com/assets/2482050/8484597/81769cfc-20c6-11e5-8f2c-0e61d1026002.jpg)

**Comment by justincone** [comment]
Just pinging this issue, as I've had several users complaining about it now. Note that this is a universal issue (not specific to browser/platform) as far as I can tell. 

Thank you!

**Comment by justincone** [comment]
I found a site that has apparently figured out a way around this bug. Might be useful as a reference:

http://alpha-channel.tv/posts/verizon-animations

**Comment by davekiss** [comment]
Good news! This long-standing issue has been corrected in the Vimeography 2 rewrite since we are using Vimeo's supported javascript library to load new videos into the same embed iframe.
