### ISSUE TITLE
CURL error behind proxy

### ISSUE THREAD

**Issue by ReneLuecking** [davekiss/vimeography#48]
Today I installed Vimeography in our company intranet which is behind a proxy. After adding the first Gallery I got the following error:

`Vimeography Fehler:the request to Vimeo failed. CURL Error:Could not resolve host: api.vimeo.com`

To prevent this, you should use the WordPress proxy constants (see https://www.danbishop.org/2013/10/14/using-wordpress-behind-a-proxy/) in your curl request:

```php
// vimeography/vendor/davekiss/vimeo-php/vimeo.php:122
private function _request($url, $curl_opts = array()) {
    //  Apply the defaults to the curl opts.
    $curl_opt_defaults = array(
        CURLOPT_HEADER         => 1,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_PROXY          => WP_PROXY_HOST . ':' . WP_PROXY_PORT,
        CURLOPT_PROXYUSERPWD   => WP_PROXY_USERNAME . ':' . WP_PROXY_PASSWORD,
        CURLOPT_NOPROXY        => WP_PROXY_BYPASS_HOSTS,
    );

    ...
}
```

Alternatively you could add a WordPress filter for your curl_opt_defaults so others can hook in it and add the proxy:

```php
$curl_opt_defaults = apply_filters('vimeography_curl_opt_defaults', array(
        CURLOPT_HEADER         => 1,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_SSL_VERIFYPEER => false
));
```

**Comment by davekiss** [comment]
@ReneLuecking thanks for the detailed report. The second suggestion sounds like a good approach.
