### ISSUE TITLE
Gallery created with Vimeo Channel links no longer working 

### ISSUE THREAD

**Issue by TheBrockEllis** [davekiss/vimeography#50]
Hi there!

One of my clients had set up their gallery to use a link from Vimeo for a 'channel' page. I'm not sure if it has something to do with 2.0 of Vimeography, or if it has to do with Vimeo's introduction of Workspaces/projects and albums, but my client was getting an error on their Wordpress site saying `
This video gallery couldn't be loaded. the Vimeo source for this gallery does not have any videos.`. 

I recreated the gallery using the 'album' link and things seem to work again. Just wanted to open an issue for future references and see if there was some user-error involved (i.e. should we not be using the channel URLs?).

Thanks for the awesome plugin!

**Comment by davekiss** [comment]
Channels are supported, this is likely due to a domain restriction or privacy setting on your videos. Please see the following article for a fix: https://docs.vimeography.com/article/38-how-do-i-display-my-private-hidden-restricted-videos
