### ISSUE TITLE
'URLSearchParams' undefined in IE/Edge

### ISSUE THREAD

**Issue by TheBrockEllis** [davekiss/vimeography#51]
Hello there!

I'm having issues with Vimeography in IE11 and Edge. The gallery is not displaying in the page on those two particular browsers nor is the gallery settings page, but it works perfectly fine in Chrome, Safari, and Firefox. The error is only appearing on the Wordpress pages where the shortcode is embedded. 

![vimeography](https://user-images.githubusercontent.com/1606194/38387665-2c4377cc-38de-11e8-983b-a3fb5ce1ed10.PNG)

Not working in:
IE 11.309.16299.0
Edge 41.16299.248.0

Working in:
Firefox Quantum 59.0.2
Chrome 63.0.3239.132
Safari 11.0.3

Any idea how to remedy this problem? Willing to submit pull requests if we can narrow down the issue.

**Comment by davekiss** [comment]
@TheBrockEllis thanks for the detailed report. This issue was corrected in 632d2a32b50f6226b007b01792f147b0c14f6dc3 and will be deployed today in Vimeography version 2.0.3
