### ISSUE TITLE
Vimeo failed. Unable to complete request.

### ISSUE THREAD

**Issue by Nick0n** [davekiss/vimeography#53]
For last few days my webpage started getting errors like this:
```
This video gallery couldn't be loaded.
the request to Vimeo failed. Unable to complete request.[error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version]
```
Once it started to appear I updated to the newest version `2.0.8`, but the problem still occurs.
I have configured a gallery with a URL to Vimeo gallery.

I tried both templates and:
 - on Bugsauce I have the mentioned error - check link: https://zubkiewicz.pl/studniowki/
 - on Harvestone I am timed out each time (but same problem occurs when I try to create a new gallery with this template) - check link: https://zubkiewicz.pl/wesela/
So I believe it's not a template issue...

**[edit][solution]**

Ok... I found the solution. Problem was caused by too old version of OpenSSL. I changed PHP version to 7.2 on my hosting what indicated updating OpenSSL as well. Now everything works fine. You can close the issue.

**Comment by davekiss** [comment]
Upgrading OpenSSL is definitely the way to fix this issue.

Your server team is the only one who can fix this issue – they need to upgrade the version of TLS that your cURL installation uses to version 1.2 – 1.0 is not a safe method of making HTTP requests.

This link may also be helpful: https://support.stripe.com/questions/how-do-i-upgrade-my-openssl-to-support-tls-1-2
