### ISSUE TITLE
Undefined Indices in Vimeography Pro

### ISSUE THREAD

**Issue by jaredforth** [davekiss/vimeography#58]
Just added Vimeography Pro and the Vimeography Developer Bundle plugins to a WordPress 5.3.2 install running on PHP 7.0.33, and every page that has a Vimeography Gallery on it displays the following error messages: 

```
Notice: Undefined index: per_page in /public_html/rivalmind/wp-content/plugins/vimeography-pro/lib/core/pro.php on line 184

Notice: Undefined index: allow_downloads in /public_html/rivalmind/wp-content/plugins/vimeography-pro/lib/renderer.php on line 40

Notice: Undefined index: playlist in /public_html/rivalmind/wp-content/plugins/vimeography-pro/lib/renderer.php on line 47

Notice: Undefined index: enable_search in /public_html/rivalmind/wp-content/plugins/vimeography-pro/lib/renderer.php on line 50
```

It was working fine with the free Vimeography Plugin, and I am using the Vimeography block to put the gallery on the page. 

What is causing this?

**Comment by jaredforth** [comment]
It looks like every instance is a call to `$this->gallery_settings['the_index']` where `the_index` is one of 
> per_page,  allow_downloads, playlist, or enable_search

These errors display even if I check the respective fields in _Gallery Editor > Vimeography Pro_.

**Comment by davekiss** [comment]
@jaredforth thanks for your report – this probably has something to do with a strict check in either a PHP config or PHP7

You can fix this by adding additional checks to ensure the indices exist before accessing them. For example, in `vimeography-pro/lib/renderer.php` on line 40

```
        'downloads' => array(
          'enabled' => array_key_exists('allow_downloads', $gallery_settings) && $gallery_settings['allow_downloads'] === 1,
        ),
```

I'll add this to the codebase for the offending lines and include it in the next update.

**Comment by jaredforth** [comment]
@davekiss Thanks!

**Comment by davekiss** [comment]
Closed via https://github.com/davekiss/vimeography-pro/commit/cec0efb366ec94787a920536e5e8bc5375c4fc57
