### ISSUE TITLE
set_galleries_per_page does not return set-screen-option filtered status

### ISSUE THREAD

**Issue by Pebblo** [davekiss/vimeography#61]
Hi there,

I'm one of the support team from @eventespresso and we recently ran into an issue with Vimeography preventing our per_page option from updating.

After a little digging, I found that the [callback function](https://github.com/davekiss/vimeography/blob/master/lib/admin/menu.php#L223-L228) on the `set-screen-option` filter doesn't return the filtered status so it nulls any other options that aren't whitelisted from within [set_screen_options()](https://developer.wordpress.org/reference/functions/set_screen_options/).

This caused a 302 redirect on our list table which then meant no $_POST values and no per-page update.

PR to return status #62

**Comment by davekiss** [comment]
@Pebblo sorry for the trouble, thank you for your contribution!
